/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaGGestion.java
 *
 * Created on 23-nov-2011, 23:27:34
 */
package Vista.Nivel1;

import Vista.Modelos.GestionarModelo;
import Vista.Modelos.BaseTableModel;
import Vista.Nivel2.FichaGBase;
import Controlador.Controlador;
import Controlador.Evento;
import Controlador.GestorEventos;
import Controlador.TipoEvento;
import java.beans.PropertyChangeEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author nanohp
 */
public class VistaGGestion extends javax.swing.JInternalFrame implements GestionarModelo, GestorEventos {

    private FichaGBase fichaElemento;
    private Controlador controlador;
    boolean administrador;
    private ParametrizadorGestion parametrosGestion;
    private BaseTableModel tableModel;

    /** Creates new form VistaGGestion */
    public VistaGGestion(Controlador controlador, ParametrizadorGestion parametrosGestion, FichaGBase fichaGBase, boolean administrador) {
        //this.listaCategoriasDewey = listaCategoriasDewey;
        this.fichaElemento = fichaGBase;
        this.parametrosGestion = parametrosGestion;
        this.controlador = controlador;
        this.administrador = administrador;
        tableModel = parametrosGestion.getBaseTableModel();

        initComponents();
        inicializaComponentesPropios();
    }

    private void inicializaComponentesPropios() {
        setTitle(parametrosGestion.getTitulo());

        tableModel = parametrosGestion.getBaseTableModel();

        jTableListado.setModel(parametrosGestion.getBaseTableModel());
        jTableListado.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);


        /* Controla la visibildad del boton para altas de titulo
         * depediendo de si el usuario es administrador o no
         */
        if (administrador) {
            jButtonNuevo.setVisible(true);
        } else {
            jButtonNuevo.setVisible(false);
        }
    }

    @Override
    public void setVisible(boolean visible) {
        super.setVisible(visible);
        ocultaBotonesAccion();
    }

    public void ocultaBotonesAccion() {
        try {
            jButtonMostrar.setVisible(false);
            jButtonModificar.setVisible(false);
            jButtonBaja.setVisible(false);
        } catch (NullPointerException e) {
            System.err.println("Error en ocultaBotonesAccion");
        }
    }

    // Implementacion de los metodos de 'GestionarModelo'
    @Override
    public void fijarModelo(Object object) {
        assert (object.getClass().getName().endsWith(".Catalogo")) : "fijarModelo: clase suminastrada invalida";

        //Catalogo catalogo= (Ba) object;
        parametrosGestion.getBaseTableModel().initModel(object);
        jTableListado.setModel(parametrosGestion.getBaseTableModel());
        jTableListado.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

    }

    @Override
    public BaseTableModel obtenerModelo() {
        return parametrosGestion.getBaseTableModel();
    }

    @Override
    public void limpiarModelo() {
        tableModel = null;
    }

    @Override
    public void setEditable(boolean esEditable) {
        tableModel.setEditable(esEditable);
    }

    @Override
    public void setModo(String modo) {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListado = new javax.swing.JTable();
        jButtonAceptar = new javax.swing.JButton();
        jButtonMostrar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonBaja = new javax.swing.JButton();
        jButtonNuevo = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestión");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/catalogo_20.png"))); // NOI18N

        jTableListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableListado.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListado);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonMostrar.setText("Mostrar");
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonBaja.setText("Baja");
        jButtonBaja.setToolTipText("");
        jButtonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaActionPerformed(evt);
            }
        });

        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                        .addComponent(jButtonMostrar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBaja)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModificar)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonBaja)
                    .addComponent(jButtonNuevo)
                    .addComponent(jButtonMostrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jTableListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListadoMouseClicked
        int pos = jTableListado.getSelectedRow();
        boolean visible = pos > -1 ? true : false;
        jButtonMostrar.setVisible(visible);

        if (administrador) {
            jButtonModificar.setVisible(visible);
            jButtonBaja.setVisible(visible);
        }
    }//GEN-LAST:event_jTableListadoMouseClicked

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed

        int filaSeleccionada = jTableListado.getSelectedRow();
        if (filaSeleccionada > -1) {
            System.out.println("--:" + tableModel.getInfo(filaSeleccionada));
            fichaElemento.fijarModelo(tableModel.getInfo(filaSeleccionada));
            fichaElemento.setModo("mostrar");
            fichaElemento.setVisible(true);
        }

    }//GEN-LAST:event_jButtonMostrarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        int filaSeleccionada = jTableListado.getSelectedRow();
        if (filaSeleccionada > -1) {
            System.out.println("--:" + tableModel.getInfo(filaSeleccionada));
            fichaElemento.fijarModelo(tableModel.getInfo(filaSeleccionada));
            fichaElemento.setModo("modificar");
            fichaElemento.setVisible(true);
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

private void jButtonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaActionPerformed
    int filaSeleccionada = this.jTableListado.getSelectedRow();
    if (filaSeleccionada > -1) {
        System.out.println("--:" + tableModel.getInfo(filaSeleccionada));
        fichaElemento.fijarModelo(tableModel.getInfo(filaSeleccionada));
        fichaElemento.setModo("baja");
        fichaElemento.setVisible(true);
    }
/*
    Object elemento = tableModel.getInfo(filaSeleccionada);
    String cadena = elemento.toString();
    String mensaje = "¿Desea borrar el título?";
    String tituloStr = "Borrado de xxxx: " + cadena;

    int respuetaInt = JOptionPane.showConfirmDialog(null, mensaje, tituloStr, JOptionPane.YES_NO_OPTION);
    if (respuetaInt == JOptionPane.YES_OPTION) {
        Evento evento = new Evento(parametrosGestion.getEventoBaja(), elemento, this);
        controlador.procesarEvento(evento);
    }*/
}//GEN-LAST:event_jButtonBajaActionPerformed

private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
    int filaSeleccionada = jTableListado.getSelectedRow();
    System.out.println(filaSeleccionada);
    if (filaSeleccionada > -1) {
        System.out.println("--:" + tableModel.getInfo(filaSeleccionada));
        fichaElemento.fijarModelo(tableModel.getInfo(filaSeleccionada));
        fichaElemento.setModo("alta");
        fichaElemento.setVisible(true);
    }
}//GEN-LAST:event_jButtonNuevoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonBaja;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListado;
    // End of variables declaration//GEN-END:variables

    @Override
    public void modelPropertyChange(PropertyChangeEvent evt) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void procesarEvento(Evento evento) {
        TipoEvento tipoEvento = evento.getTipoEvento();

        switch (tipoEvento) {

            
            default:
                throw new AssertionError(tipoEvento + ": Evento no controlado");
        }
    }
}
